server:
  port: 28088
zuul:
  routes:
    image:
      path: /images/**
      url: http://localhost/images/
    user:
      path: /user/**
      url: http://localhost:28089/
    root:
      path: /s1/**
      url: http://localhost:18081/
    prud:
      path: /s/**
      url: http://localhost/s/
spring:
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: -1
        max-idle: 4
